### PR TITLE
Add colander library

### PR DESCRIPTION
**Pull request by kwilcox**

### CODE REVIEW

**Comment by ocefpaf** [comment]
@kwilcox for future reference just add something about these libraries you are adding.  Like: it is a dependency for...

**Comment by ocefpaf** [comment]
Also, it seems you are on a roll in there.  So ping me once you are done and I will start the docker builds.

**Comment by rsignell-usgs** [comment]
Agreed.   We should have some idea why we need this stuff.   And although @kwilcox has a proud tradition of no documentation  he was recently heard to say that he now finds it useful to remember what he was doing two weeks ago. :smile_cat:

**Comment by kwilcox** [comment]
hey hey hey now, documentation is getting much better!

These are all requirements for https://github.com/NOAA-ORR-ERD/PyGnome. Chris had a bunch in conda already, but only for a mix of osx-64 and win-64.

**Comment by ChrisBarker-NOAA** [comment]
Note:

I'm trying to manage everything that PyGnome needs here:

https://github.com/NOAA-ORR-ERD/orr-conda-recipes
The idea is that I want to be able to tell my users to add a single channel to conda, and be able to get eveything they need.

But I am currently running obvious-ci on local machines to build the packages, which is why I've only got some platforms up there (no users asking for Linux packages yet -- we're not using conda on Linux)

but this semi-chaos of various folks maintaining repos of overlapping packages is less than ideal. So we should all move this to conda-forge at some point:

https://github.com/conda-forge

**Comment by kwilcox** [comment]
Totally agree with using `conda-forge`... still waiting for that 5 minute tutorial since I missed SciPy this year!

After I get the linux-64 build of PyGnome up and running I'll make sure the configs end up back in https://github.com/NOAA-ORR-ERD/orr-conda-recipes.

**Comment by ocefpaf** [comment]
@ChrisBarker-NOAA I am running out of excuses to not use conda-forge.  All need is some free time and I will port the whole IOOS channel there.

**Comment by ChrisBarker-NOAA** [comment]
@kwilcox : Are you using Anaconda on Linux? cool!

If so, it would be great if you could test the recipes in 
https://github.com/NOAA-ORR-ERD/orr-conda-recipes on Linux

I'd be happy to give you permissions to push to the channel, too, if you want to do it that way.

**Comment by ocefpaf** [comment]
Just to let you know.  I am hitting some issues for the Linux builds see below).  I will keep trying...

```python
Traceback (most recent call last):
  File "/opt/conda/bin/obvci_conda_build_dir.py", line 30, in <module>
    cls(getattr(args, 'recipe-dir'), getattr(args, 'upload-user'), args.channel).main()
  File "/opt/conda/lib/python2.7/site-packages/obvci/conda_tools/build_directory.py", line 144, in main
    existing_distributions = self.calculate_existing_distributions(recipe_metas)
  File "/opt/conda/lib/python2.7/site-packages/obvci/conda_tools/build_directory.py", line 131, in calculate_existing_distributions
    if inspect_binstar.distribution_exists(self.binstar_cli, self.upload_owner, meta)]
  File "/opt/conda/lib/python2.7/site-packages/obvci/conda_tools/inspect_binstar.py", line 15, in distribution_exists
    fname)
  File "/opt/conda/lib/python2.7/site-packages/binstar_client/__init__.py", line 329, in distribution
    res = self.session.get(url)
  File "/opt/conda/lib/python2.7/site-packages/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "/opt/conda/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/conda/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/opt/conda/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', gaierror(-3, 'Temporary failure in name resolution'))
```

**Pull request merged**
