### PR TITLE
Updated Shapely to 1.5.11

### PR DESCRIPTION
**Pull request by ocefpaf**
1.5.11
-------------------
- Replace packaging.version with distutils.version

1.5.10 (2015-??-??)
-------------------
- Monkey patch affinity module by absolute reference (#299).

### CODE REVIEW

**Comment by ocefpaf** [comment]
@rsignell-usgs **Do not merge this yet!!!**

I am just testing the latest shapely.

**Comment by ocefpaf** [comment]
@pelson should I send this to conda-recipes-scitools as well?  Having the latest Shapely available in our channels  prevents conda from downloading the default channel package (which is compiled geos-3.3.3 and breaks cartopy).

PS: Shapely+geos will be my first conda-forge packages!  Just need some time...

**Comment by pelson** [comment]
> Having the latest Shapely available in our channels prevents conda from downloading the default channel package (which is compiled geos-3.3.3 and breaks cartopy).

Ok. We fix that with features...

cartopy/meta.yaml

```
build:
  track_features:
    - correct_GEOS_identification_in_shapely  # [osx]
```

shapely/meta.yaml
```
build:
  features:
    - correct_GEOS_identification_in_shapely  # [osx]
```

A bit of testing might mean we only need the features and track_features in the shapely recipe, and that would be enough...
I've not played with features much, and don't know how well obiviousci will deal with them at this point.

**Comment by ocefpaf** [comment]
> I've not played with features much, and don't know how well obiviousci will deal with them at this point.

Neither have I and, to be honest, it would be better if we could push `geos-3.4.2` and the `shapely` patch to the default channel.  I prefer to a "fix this" than "fix my case."

**Comment by pelson** [comment]
Ping @asmeurer / @ilanschnell - I don't believe you are packaging shapely correctly (it requires a patch, as per this repo), and you are shipping an old GEOS. Any chance you could fix this?

**Comment by asmeurer** [comment]
@groutr

**Pull request merged**
