### PR TITLE
elminating duplicate and conflicting build versions for sci-wms

### PR DESCRIPTION
**Pull request by rsignell-usgs**

### CODE REVIEW

**Comment by ocefpaf** [comment]
:scream:

**Comment by rsignell-usgs** [comment]
@ocefpaf, can you do the linux build?

**Comment by ocefpaf** [comment]
Sure.  Can you merge #324 and #325 before?  That way I have to run docker just once :wink:

**Comment by rsignell-usgs** [comment]
done!

**Comment by ocefpaf** [comment]
... and done!

**Comment by rsignell-usgs** [comment]
Not seeing it here:
https://binstar.org/IOOS/sci-wms/files

**Comment by ocefpaf** [comment]
All those releases are there (0, 2, 3).  See #328 for the latest version (release 0).

**Pull request merged**
