### PR TITLE
Add redis-py bindings (for windows)

### PR DESCRIPTION
**Pull request by daf**
Builds a package named redis-py, needed for #301

### CODE REVIEW

**Comment by ocefpaf** [comment]
Will this work without a redis server?  If not this package is broken!

**Comment by daf** [comment]
@ocefpaf, I don't understand the question.  This is a client library to connect to a redis server, why would I have to package a server as well?  What do you mean by "work without"?

**Comment by ocefpaf** [comment]
The official conda `redis-py` package depends on `redis-2.6.9`.  Maybe they think that people will use this locally to create a local server and use `redis-py`, maybe `redis-py` needs `redis`... I don't know because I am not a `redis` user.

If you really do not need `redis` to get `redis-py` working, then I am puzzled why continuum does not provide the Windows package as well...

**Comment by daf** [comment]
Closing in favor of marking redis an optional dependency of paegan-transport in #301 (which it is).

**Pull request closed without merging**
