### PR TITLE
Test

### PR DESCRIPTION
**Pull request by ocefpaf**
Fix for #534 

@jorisvandenbossche can you test the binaries once the packages lands on the channel?  I don't have a Win64 machine.

### CODE REVIEW

**Comment by jorisvandenbossche** [comment]
Yes, it works now for windows/64bit/python3 !
Thanks

**Comment by ocefpaf** [comment]
Awesome!  Thanks for testing.

**Comment by jorisvandenbossche** [comment]
Out of curiosity: what did fix this issue? Was it a bug in pyproj that is fixed by using master, or was it an issue in the packaging? (can the issue I reported to pyproj be closed? https://github.com/jswhit/pyproj/issues/17)

**Comment by ocefpaf** [comment]
We have two different packing issues there:

- The default channel compiles pyproj against their version of proj.4 rather than the custom source shipped with pyproj's source.  That is the reason why the default channel is missing some features. (I added a [test](https://github.com/ocefpaf/conda-recipes/blob/5660cffc332b24ddbc4719d9e8e88c48364939a3/pyproj/run_test.py#L4-L5) to ensure we will always have the EPSG data in our package.)

- Pyproj 1.9.4 did not use setuptools and was hitting a bug in `distutils` that Python folks did not considered a [bug](https://bugs.python.org/issue4431).

A long time ago I tried to fix that in pyproj by adding setuptools, but my PR never moved [forward](https://github.com/jswhit/pyproj/pull/2). Luckily someone else did [this](https://github.com/jswhit/pyproj/pull/21) properly and that version of the PR got merged.

**Comment by jorisvandenbossche** [comment]
Thanks for the explanation!

**Pull request merged**
