### PR TITLE
ESMF 7.0.0

### PR DESCRIPTION
**Pull request by ocefpaf**
Ping @bekozi.

### CODE REVIEW

**Comment by bekozi** [comment]
Wow, thanks @ocefpaf! This was on my todo list. I'll send a PR for running MPI tests with an external script when I get it put together.

**Comment by ocefpaf** [comment]
I want o try [this](https://gist.github.com/rokuingh/811d91ed6ce7264f6415) out and I guess I need ESMF 7.0.0 :wink:

**Comment by ocefpaf** [comment]
@bekozi I cannot find the file http://www.earthsystemmodeling.org/download/data/ne30np4-t2UGRID_nodual.nc mentioned in that example.  Can you help me find it?

**Comment by bekozi** [comment]
@rokuingh is the keeper of this data. He'll have to help us.

**Comment by ocefpaf** [comment]
Thanks!  (I am trying to make a notebook out of that gist to demo ESMF.)

**Comment by ocefpaf** [comment]
Thanks @bekozi and @rokuingh.  Here is the notebook version of that example:

http://nbviewer.jupyter.org/gist/ocefpaf/dd282b7fe705b3755e00

Ping @rsignell-usgs.  Now we need some real data example with IOOS models :wink:

**Pull request merged**
