### PR TITLE
Fiona

### PR DESCRIPTION
**Pull request by ocefpaf**
Fiona is broken in the default channel.  It is compiled against  `gdal 2.0.0`, which is known to not work properly with fiona, and is missing two core dependencies: `munch` and `click-plugins`.

This PR re-introduces fiona in the ioos channel to avoid headaches like #623.

### CODE REVIEW

**Comment by fmaussion** [comment]
Thanks for spending time on this, a working conda version of Fiona would be very useful

**Comment by ocefpaf** [comment]
> Thanks for spending time on this, a working conda version of Fiona would be very useful

The hard part is to make a new build of `gdal 1.11.2` for `numpy 1.10`.  The standard channel has `gdal 1.11.2` only up to `numpy 1.9`.

**Comment by ocefpaf** [comment]
The OSX log is so long that Travis-CI is truncating it and I have no idea where is the failure.

Do we have any Mac owners following this issue to volunteer themselves to test this recipe?

**Comment by jorisvandenbossche** [comment]
+1000 This would solve a lot of headaches installing geopandas and the like!

**Comment by rsignell-usgs** [comment]
@ocefpaf , any hope for the windows version?
https://ci.appveyor.com/project/comtbot/conda-recipes/build/1.0.1517/job/35tbihnn5f5p6rtu#L1368

**Comment by ocefpaf** [comment]
I will take a better look tomorrow.  Today I took a day off for folium.  (Version `v0.2.0` is almost out!)

**Comment by ocefpaf** [comment]
Ironically I building `gdal`+`fiona` on Windows was easier than OSX.

I am merging this without OSX hoping a volunteer shows up to try to fix https://github.com/ioos/conda-recipes/issues/629. (Unless someone is willing to donate a Mac to ioos conda-recipes :stuck_out_tongue_winking_eye:)

**Pull request merged**
