### PR TITLE
Testing pysgrid

### PR DESCRIPTION
**Pull request by ocefpaf**
@ayan-usgs and @rsignell-usgs this PR is just some boilerplate for a future `pysgrid` package.  As soon as we get an official release we can merge it.

### CODE REVIEW

**Comment by rsignell-usgs** [comment]
@ocefpaf , sounds good.

**Comment by rsignell-usgs** [comment]
I think the first real use case is using pysgrid within sci-wms to plot vectors from ROMS.   I think @ayan-usgs is getting close.

**Comment by ayan-usgs** [comment]
@ocefpaf,

Thanks for putting this together.

@rsignell-usgs: Yep, I feeling like we're getting pretty close.

**Comment by ocefpaf** [comment]
Closing this while we wait for an official release.

Note to self: Add `pysgrid` as a dependency to `sci-wms`.

**Pull request closed without merging**
