### PR TITLE
Added siphon

### PR DESCRIPTION
**Pull request by ocefpaf**
# Siphon
- Siphon - A collection of Python utilities for retrieving data from Unidata data technologies.

An example from a mailing list:

```python
# Resolve the latest HRRR dataset
from siphon.catalog import TDSCatalog
latest_hrrr = TDSCatalog('
http://thredds-jumbo.unidata.ucar.edu/thredds/catalog/grib/HRRR/CONUS_3km/surface/latest.xml
')
hrrr_ds = list(latest_hrrr.datasets.values())[0]

# Set up access via NCSS
from siphon.ncss import NCSS
ncss = NCSS(hrrr_ds.access_urls['NetcdfSubset'])

# Create a query to ask for all times in netcdf4 format for
# the Temperature_surface variable, with a bounding box
query = ncss.query()
query.all_times().accept('netcdf4').variables('Temperature_surface')
query.lonlat_box(45, 30, -100, -90)

# Get the raw bytes and write to a file.
data = ncss.get_data_raw(query)
with open('test.nc', 'wb') as outf:
    outf.write(data)
```

### CODE REVIEW

**Comment by rsignell-usgs** [comment]
I'm not sure I understand the utility of this package.   Why would you get data via NCSS instead of OPeNDAP?

Are you using it?

**Comment by ocefpaf** [comment]
I am experimenting with it for now.  Hold off the merge until we know that this is useful for a broader audience.

**Comment by rsignell-usgs** [comment]
@ocefpaf , have you determined whether this is faster than OPeNDAP?  
Maybe that's the usefulness?

**Comment by ocefpaf** [comment]
I haven't had time to play with this package yet.

Maybe I will cram that into my extra leap-second for today :wink: 

<sarcasm> The docs are amazing!!!</sarcasm>  See: http://siphon.readthedocs.org/en/stable/

PS: Based on the code example above I believe the usefulness is to explore the catalog directly.  Not sure though...

**Comment by emiliom** [comment]
@ocefpaf, I can see that you probably were able to use the extra leap second to read the entire documentation ...

I haven't checked out siphon either, but it's in my indefinite to-do list to find a decent module to explore THREDDS catalogs. I haven't tried thredds_crawler either (and I see it's on the ioos channel), but I now wonder which one to invest time on. I would hope a package from unidata would be better in the long run ...

**Comment by ocefpaf** [comment]
>  I can see that you probably were able to use the extra leap second to read the entire documentation ...

Twice actually :wink: 

Both are on my list too.  If I ever write about them I'll ping you for a review.

**Comment by cehbrecht** [comment]
i was looking for a tool to navigate in thredds catalogs and retrieve metadata and access urls. First i tried the `thredds_crawler` ... easy to find on pypi ;) But the `thredds_crawler` does not only parse thredds catalog xml pages but also runs an extra query for each found dataset (with dataset_id). That puts quite some traffic on the thredds server and i have not seen a case where the dataset queries gives more information ...

Then i found the `threddsclient` from ScottWales ... it was half finished but more in the way i wanted it ... so i worked on that one: https://github.com/bird-house/threddsclient

After if have done this i found `siphon` ;) So, my hope is that `siphon` will provide the functionality i want ... but it is still work in progress. They already know about `threddsclient` and Scott seams also to have started to work on `siphon`.

**Pull request merged**
