### PR TITLE
Updated oceans

### PR DESCRIPTION
**Pull request by ocefpaf**
Updated to latest release

### CODE REVIEW

**Comment by rsignell-usgs** [comment]
So oceans was the culprit for geos 3.3?
Do you need to restart appveyor?

**Comment by ocefpaf** [comment]
Nope, but oceans calls cartopy and it was failing when cartopy pulled geos 3.3.3

I am puzzled by how conda deals dependencies.  I cannot see why geos 3.3.3 gets precedence over the geos 3.4.2 in the ioos channel.

**Comment by rsignell-usgs** [comment]
@ocefpaf , how about asking the conda google group, using this exact example to illustrate the problem?

**Comment by ocefpaf** [comment]
> Do you need to restart appveyor?

Nope.  Win32 worked just fine and Win64 is in the Queue.

>  How about asking the conda google group, using this exact example to illustrate the problem?

I have a draft e-mail here.  I am just waiting for these tests to finish.

**Comment by ocefpaf** [comment]
@rsignell-usgs I finally found the source of the issue!  Conda updated its default shapely to `1.5.8` (using `geos-3.3.3`).  Our shapely, `1.5.8dev0`, is compiled against `geos-3.4.2`.  The problem is that our shapely is not downloaded because `1.5.8` takes precedence over `1.5.8dev0`.

I will fix this.  Meanwhile do not merge this PR nor #214.

**Pull request merged**
