### PR TITLE
Update flopy meta.yaml

### PR DESCRIPTION
**Pull request by jdhughes-usgs**
This version has Python 3 support

### CODE REVIEW

**Comment by ocefpaf** [comment]
@jcothran I saw that you updated the metadata in your previous (closed) PR.  It would be nice the have that here too.

**Comment by rsignell-usgs** [comment]
Thanks for contributing @jdhughes-usgs !

**Comment by jcothran** [comment]
@ocefpaf  I'm not following on your comment(PR?), please explain further

**Comment by jdhughes-usgs** [comment]
Probably just related to pull request comment. Can ignore.

**Comment by ocefpaf** [comment]
Jeremy, GitHub auto-completed `@j<dhughes-usgs>` to `@j<cothran>` and I clicked "Comment" by accident.  Sorry to bug you!

**Comment by rsignell-usgs** [comment]
Heh, glad that mystery is cleared up.  I was wondering about that myself!

**Pull request merged**
