### PR TITLE
Update paegan to 1.1.3

### PR DESCRIPTION
**Pull request by ocefpaf**
No info... no changelog.

### CODE REVIEW

**Comment by rsignell-usgs** [comment]
Do you still have to build linux manually?

**Comment by rsignell-usgs** [comment]
@kwilcox , https://github.com/asascience-open/paegan/releases does not show a 1.1.3.  Can you release there as well and put some comments in about what changed?

**Comment by kwilcox** [comment]
@rsignell-usgs The ASA repo is dormant, I've been developing here: https://github.com/axiom-data-science/paegan

**Comment by rsignell-usgs** [comment]
@kwilcox , ah, okay.    Any release notes or comments about this release?   Should paegan move to github/ioos?

**Comment by ocefpaf** [comment]
> Do you still have to build linux manually?

Yep. And I am out of a decent connection until Friday.

**Comment by ocefpaf** [comment]
> @rsignell-usgs The ASA repo is dormant, I've been developing here:
https://github.com/axiom-data-science/paegan

Thanks Kyle. I will update the recipe metadata.

**Pull request merged**
