### PR TITLE
IOOS

### PR DESCRIPTION
**Pull request by ocefpaf**
Added IOOS binstar token
Changed channel from rsignell to ioos

### CODE REVIEW

**Comment by ocefpaf** [comment]
@rsignell-usgs Do not merge this yet.  Because the IOOS binstar channel is empty we will see some unexpected packages issue surfacing.  I will fix them in this same PR later.

**Comment by ocefpaf** [comment]
First wall.  Somehow obvci_conda_build_dir.py puts `compliance-checker` before `owslib` in the travis build (surprisingly it order them correctly locally!)  and because `compliance-checker` depends on `owslib` travis exit with an error.

https://s3.amazonaws.com/archive.travis-ci.org/jobs/50774338/log.txt

PS: Actually, the build order seems to be alphabetical and not depence-chain in travis.  @pelson if you have some time could you shed some light of what I am doing wrong here.

**Comment by rsignell-usgs** [comment]
Bummer.  Hoping for @pelson on white horse...

**Comment by ocefpaf** [comment]
Here is the "right" build sequence, when I try it locally:

```bash
obvci_conda_build_dir.py ./ ioos --channel main
Looking for packages in ./
**Build will continue, but no uploads will take place.**
To automatically upload from this script, define the BINSTAR_TOKEN env variable.
This is done automatically on the travis-ci system once the PR has been merged.
Resolved dependencies, will be built in the following order:
        affine (will be built: True)
        airsea (will be built: True)
        appdirs (will be built: True)
        beautifulsoup4 (will be built: True)
        biggus (will be built: True)
        boost (will be built: True)
        brewer2mpl (will be built: True)
        cdat-lite (will be built: True)
        click (will be built: True)
        cligj (will be built: True)
        cov-core (will be built: True)
        csa (will be built: True)
        docopt (will be built: True)
        enum34 (will be built: True)
        epic2cf (will be built: True)
        fiona (will be built: True)
        flopy (will be built: True)
        folium (will be built: True)
        gensim (will be built: True)
        geojson (will be built: True)
        geolinks (will be built: True)
        geos (will be built: True)
        iptools (will be built: True)
        iso8601 (will be built: True)
        isodate (will be built: True)
        jasper (will be built: True)
        jsanimation (will be built: True)
        jsonfield (will be built: True)
        libmo_unpack (will be built: True)
        libspatialindex (will be built: True)
        mpld3 (will be built: True)
        mplexporter (will be built: True)
        mplleaflet (will be built: True)
        mysql-python (will be built: True)
        nn (will be built: True)
        octant (will be built: True)
        optcomplete (will be built: True)
        petulant-bear (will be built: True)
        prettyplotlib (will be built: True)
        proj4 (will be built: True)
        pyepsg (will be built: True)
        pygridgen (will be built: True)
        pyke (will be built: True)
        pymc (will be built: True)
        pyproj (will be built: True)
        pyshp (will be built: True)
        pytest-cov (will be built: True)
        python-dateutil (will be built: True)
        pyugrid (will be built: True)
        rasterio (will be built: True)
        rdflib (will be built: True)
        rtree (will be built: True)
        sci-wms-deps (will be built: True)
        scp (will be built: True)
        seawater (will be built: True)
        shapely (will be built: True)
        south (will be built: True)
        sparqlwrapper (will be built: True)
        suds (will be built: True)
        tappy (will be built: True)
        thredds_crawler (will be built: True)
        udunits2 (will be built: True)
        udunitspy (will be built: True)
        ulmo (will be built: True)
        wheel (will be built: True)
        wicken (will be built: True)
        workerpool (will be built: True)
        cfchecker (will be built: True)
        coveralls (will be built: True)
        delocate (will be built: True)
        ecmwf_grib (will be built: True)
        gridutils (will be built: True)
        owslib (will be built: True)
        paegan (will be built: True)
        pycsw (will be built: True)
        pygdp (will be built: True)
        pyhum (will be built: True)
        pyoos (will be built: True)
        pytools (will be built: True)
        starcluster (will be built: True)
        cartopy (will be built: True)
        compliance-checker (will be built: True)
        gridgen (will be built: True)
        iris (will be built: True)
```

**Comment by ocefpaf** [comment]
Somehow, by removing the version check on compliance-checker for owslib, things worked on travis!  We are stuck witch docopt for coveralls now.  I will removed these packages for now.  I do not see a direct use in IOOS for a coverage testing right now.

**Comment by rsignell-usgs** [comment]
Should we expect Travis still failing at this point?

**Comment by pelson** [comment]
> Somehow, by removing the version check on compliance-checker for owslib, things worked on travis!

I wonder if this is the line causing the problem https://github.com/pelson/Obvious-CI/blob/master/obvci/conda_tools/build_directory.py#L79 - it may be that ``meta['requirements']['build']`` is including the version number...

**Comment by pelson** [comment]
> Should we expect Travis still failing at this point?

I suspect not. Looks like you can't build Octant without a fortran compiler.

**Comment by pelson** [comment]
> I wonder if this is the line causing the problem

Fixed with https://github.com/pelson/Obvious-CI/pull/4. Confirmed that that was the problem.

If you give travis and appveyor time to run, you will be able to pick up these changes automatically since you are using my development channel.

@ocefpaf - I'd suggest therefore re-instating the owslib version requirement - it should all now be good.

**Comment by ocefpaf** [comment]
> Should we expect Travis still failing at this point?

@rsignell-usgs yes.  And many more to come. Each package I fix I find another issue.  I will keep modifying this PR until we get all of them building.  (Take `flopy` for example, the requirements numpy and matplotlib, where not in the meta!)

Once I find all the issues I will either send separate PRs to fix each package or maybe squash this one... Lets see what is better to keep a meaningful history.

> I suspect not. Looks like you can't build Octant without a fortran compiler.

That is another break @pelson, unrelated to obvci.  Last night I kept tinkering with the metas to try to find the issue.

> Fixed with pelson/Obvious-CI#4. Confirmed that that was the problem.

Thanks @pelson!  I just wonder why

`obvci_conda_build_dir.py ./ ioos --channel main`

ordered them properly locally but not on travis-ci?

**Comment by ocefpaf** [comment]
@pelson quick question:  will Obvious-CI upload successful builds even if travis-ci fails in the end?

@rsignell-usgs If that is the case we might consider merging every change.  That way we will get faster builds every time we fix a package.

**Comment by rsignell-usgs** [comment]
Merging with every change is fine with me.

**Comment by ocefpaf** [comment]
@rsignell-usgs still, do not merge this one!  I will use this as a playground and I will send pretty PRs with the right changes soon.

**Comment by rsignell-usgs** [comment]
@ocefpaf.   Got it.  Standing by in Calais with my binoculars.

**Comment by ocefpaf** [comment]
@rsignell-usgs: tried to jump, chew, and digg (#50, #51, #52, and #53), but I will not die on the 53.  Many more to come.

PS: All should be safe to merge.

**Comment by pelson** [comment]
> will Obvious-CI upload successful builds even if travis-ci fails in the end?

Yes. Take a look at the main loop: https://github.com/pelson/Obvious-CI/blob/master/obvci/conda_tools/build_directory.py#L123
The process is build -> upload/add_to_channel -> build next -> upload ...

> Got it. Standing by in Calais with my binoculars.

*Snigger*

**Comment by ocefpaf** [comment]
Thanks @pelson. So it makes sense to keep merging as we go @rsignell-usgs (you already have a few there to review on your plate).  Each time we do that we will reduce the load on travis.

**Comment by ocefpaf** [comment]
Closed in favor of #54.

**Pull request closed without merging**
