### PR TITLE
Test netCDF4 build on Windows

### PR DESCRIPTION
**Pull request by ocefpaf**
~~Just testing.~~

The default channel is outdated (version 1.1.9 is two releases behind) and not build with Cython (so no `filepath` method).

### CODE REVIEW

**Comment by ocefpaf** [comment]
Ping @rsignell-usgs can you test this on Windows?

@kwilcox I am certain this is not a blocker for you, but `wera2netcdf` (or any other package that depends on netCDF4) is not available on Windows+Python 3.5

**Comment by pelson** [comment]
Very nice. :+1:

**Comment by ocefpaf** [comment]
I guess this should be in conda-forge.

It is sad to see some key packages lagging behind in the default channel.  We really need to strengthen the community channels and find a way to push these key packages back into the default channel.

**Comment by pelson** [comment]
> We really need to strengthen the community channels and find a way to push these key packages back into the default channel.

Maybe one day the community channel(s) should be part of the default channel. We need to get our house in order first though - I'm currently doing a *lot* of conda stuff at the moment, but none of it is directly targeted at the community channel (aka conda-forge) stuff. Once I've got my current project out of the way (which is funding some of the tools which will make conda-forge better/easier) I'll start spinning the community channel work up again in earnest. I don't expect it will be quick, but the groundswell has started and I think we will be in a very strong position in 3-6 months.

**Comment by rsignell-usgs** [comment]
@ocefpaf , how would you like this tested?

**Comment by ocefpaf** [comment]
See if you can use `nc.filepath()` and the new stuff like the `get_variables_by_attributes`.

**Comment by ocefpaf** [comment]
> Maybe one day the community channel(s) should be part of the default channel. 

I would love for the community channel(s) to become a "vetting step" to add packages to the default channel.

>  I'm currently doing a *lot* of conda stuff at the moment, but none of it is directly targeted at the community channel (aka conda-forge) stuff.

I am following from a safe distance.  You last project, conda-execute, made me spend 2 days re-writing my scripts :stuck_out_tongue_winking_eye:  (Totally worth it BTW!)

> I think we will be in a very strong position in 3-6 months.

I think that is quick!

**Comment by rsignell-usgs** [comment]
@ocefpaf , reporting back that the new netcdf4 functionality `nc.filepath()` and  `get_variables_by_attributes` work fine on Windows using python 2.7 and 3.4.   

See cell [20] and [21] here:
https://github.com/rsignell-usgs/notebook/blob/master/UGRID/FVCOM_depth_and_velocity.ipynb

:tada:

**Comment by ocefpaf** [comment]
Awesome!  Thanks.

As soon as `mingwpy` sorts python 3.5 out I will build it. For now we are limited to python 3.4 on Windows.

**Pull request merged**
