### PR TITLE
scitools owslib

### PR DESCRIPTION
**Pull request by ocefpaf**
Pulling OWSLib from scitools.

### CODE REVIEW

**Comment by ocefpaf** [comment]
Needs https://github.com/SciTools/conda-recipes-scitools/pull/125#partial-pull-merging

**Comment by emiliom** [comment]
What's the reason for pulling OWSLib from scitools? Is it simply b/c it's already being packaged there (ie, leverage that effort and reduce duplication of work on the ioos channel), or is there something more specific? Just curious. Thanks!

**Comment by ocefpaf** [comment]
> Is it simply b/c it's already being packaged there (ie, leverage that effort and reduce duplication of work on the ioos channel), or is there something more specific?

Avoiding duplication is the main goal.  Note that we (ioos) are not outsourcing the build to another channel (scitools).  We are joining forces to maintain the common recipes in one place.

**Comment by emiliom** [comment]
Thanks.

**Pull request merged**
