### PR TITLE
Using objective-c.

### PR DESCRIPTION
**Pull request by ocefpaf**
Testing to get MacOS via objective-c.

### CODE REVIEW

**Comment by ocefpaf** [comment]
@rsignell-usgs Do not merge this.  I am just playing around with a possible MacOS workaround.

**Comment by pelson** [comment]
I've been playing with circle-ci this evening - it is awesome for docker builds, so I'm going to try to pull together the pieces to do:
 * Appveyor - Windows 32 & 64
 * travis-ci - OSx via Objective-c
 * circle-ci - Linux 32 & 64 with an old glibc for compatibility.

I'm looking to do this on the scitools/conda-recipes-scitools, but almost all of the change will take place in obvious-ci so should be easy to pick up. In short, I fully expect the objective-c change being made here to be a permanent change to the .travis.yaml in the medium term.

**Comment by ocefpaf** [comment]
Awesome!!!  :joy: :joy: :joy:

(For now I am using this PR to check what is broken with our MacOS builds and, if there is any low hanging fruit, fix them.)

**Comment by rsignell-usgs** [comment]
Okay, will hold off. Fingers crossed!

**Comment by ocefpaf** [comment]
Collecting the failures:

- [ ] octant
- [ ] rtree (0.7.0)
- [ ] nco
    - [ ] nco-bindings
    - [ ] pyaxiom (nco is optional)

**Comment by ocefpaf** [comment]
OK experiment is over.  I collected all the package that are not building on Travis-ci Mac.

**Pull request closed without merging**
