### PR TITLE
bump pyaxiom to 1.0.7

### PR DESCRIPTION
**Pull request by rsignell-usgs**
there are no comments on what has changed in pyaxiom

### CODE REVIEW

**Comment by ocefpaf** [comment]
@rsignell-usgs can you rebase this one?

**Comment by rsignell-usgs** [comment]
rebase and do what?

**Comment by ocefpaf** [comment]
Just rebase against master.  A new build will start on its own.  I can do that here if you want.

**Comment by ocefpaf** [comment]
OK.  I see that your PRs are online edits.  We can just close and re-send (it will be the same as re-basing).

**Comment by ocefpaf** [comment]
Replaced by #395

**Pull request closed without merging**
