### PR TITLE
Adding nco.

### PR DESCRIPTION
**Pull request by ocefpaf**
@rsignell-usgs this will probably fail or it will produce a defective/incomplete nco.  That is because the default channel does not provide antlr nor [gsl](https://github.com/conda/conda-recipes/tree/master/gsl).

I just want to see the failure to have something to work with.

### CODE REVIEW

**Comment by ocefpaf** [comment]
@rsignell-usgs without `antlr` it could not build `ncap2`, but `DAP`, `udunits` and the rest seems OK.  Now I dare you to merge it :smiling_imp:

**Comment by ocefpaf** [comment]
@ChrisBarker-NOAA I would love to know if this works on MacOS, if you find the time...

**Comment by ocefpaf** [comment]
Humn.. Now that I added a simple test and re-based we get our first failure...

**Comment by ChrisBarker-NOAA** [comment]
I am on travel so probably not for a while. But good one to have. Ping me
again in two weeks if I haven't done it.

-Chris

On Thursday, March 26, 2015, Filipe <notifications@github.com> wrote:

> @ChrisBarker-NOAA <https://github.com/ChrisBarker-NOAA> I would love to
> know if this works on MacOS, if you find the time...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ioos/conda-recipes/pull/136#issuecomment-86657626>.
>


-- 

Christopher Barker, Ph.D.
Oceanographer

Emergency Response Division
NOAA/NOS/OR&R            (206) 526-6959   voice
7600 Sand Point Way NE   (206) 526-6329   fax
Seattle, WA  98115       (206) 526-6317   main reception

Chris.Barker@noaa.gov

**Comment by ocefpaf** [comment]
OK I got it working with the `antlr` that is available in travis-ci.  Now `nco` compiles with `ncap2` support.

I went ahead and added the [nco-bindings](https://github.com/jhamman/nco-bindings) that is used in `pyaxiom`.

@rsignell-usgs over to you to merge and test.

**Comment by rsignell-usgs** [comment]
Do we really expect this to work on windows?

**Comment by ocefpaf** [comment]
>Do we really expect this to work on windows?

No there is no `bld.bat`.  AppVeyor just runs because it our setup does not know that before AppVeyor starts.

Not that it is impossible to get `nco` on Windows.  I just don't know what it would take to do it.

**Pull request merged**
