### PR TITLE
Step 0 for pyferret

### PR DESCRIPTION
**Pull request by ocefpaf**
@emiliom netcdf-fortran is one of the dependencies need by pyferret.

### CODE REVIEW

**Comment by emiliom** [comment]
Hopefully netcdf-fortran will be of wider use, beyond pyferret ...

**Comment by ocefpaf** [comment]
> Hopefully netcdf-fortran will be of wider use, beyond pyferret

Probably yes.  I've been meaning to package this for a while.  However, after reading all the instructions for pyferret I am afraid it is not worth the effort.  Sorry :disappointed_relieved:

**Comment by emiliom** [comment]
No worries. Thanks for investigating this.

**Comment by ocefpaf** [comment]
OK.  Let's get `netcdf-fortran` interface merged.

**Pull request merged**
