### PR TITLE
Circle-CI

### PR DESCRIPTION
**Pull request by ocefpaf**
Added Circle-CI build.

### CODE REVIEW

**Comment by ocefpaf** [comment]
@kwilcox and @rsignell-usgs no more manual docker builds for Linux64.

**Comment by ocefpaf** [comment]
@jjhelmus I remember you asking about our Linux builds.  Check this PR out and the `Dockerfile` below in case you want to drop vagrant for docker.

https://hub.docker.com/r/ocefpaf/centos64-conda-obvious-ci/~/dockerfile/

```dockerfile
FROM centos:6

MAINTAINER Filipe Fernandes <ocefpaf@gmail.com>

RUN yum -y update && yum clean all

# Some build tools.
RUN yum install -y tar bzip2 patch file make gcc-c++ wget git libtool texinfo
RUN yum groupinstall -y 'Development Tools'

RUN wget http://bit.ly/miniconda -O miniconda.sh
RUN bash miniconda.sh -b -p /opt/conda && rm miniconda.sh
RUN /opt/conda/bin/conda update --yes --all
RUN /opt/conda/bin/conda config --add channels ioos --force
RUN /opt/conda/bin/conda install -c http://conda.binstar.org/pelson/channel/development --yes --quiet obvious-ci
RUN PATH=/opt/conda/bin:$PATH obvci_install_conda_build_tools.py

# Qt, matplotlib, and vispy.
RUN yum install -y libXext libSM libXrender fontconfig mesa-libGL

# octant.
RUN yum install -y gcc-gfortran

# udunits2.
RUN yum install -y expat-devel

# nco.
RUN yum install -y bison byacc flex gsl-devel antlr

ENV PATH /opt/conda/bin:$PATH
```

We fully automate Linux-64, OSX, Win-32/64 now.

**Comment by pelson** [comment]
FWIW @ocefpaf, inspired by your Dockerfile, I have a fork of it in ObviousCI: https://github.com/pelson/Obvious-CI/blob/master/obvious-ci.docker/linux64_obvci/Dockerfile

**Comment by ocefpaf** [comment]
> I have a fork of it in ObviousCI:

Yours is much cleaner and I think we should focus our effort there.  The "extra" stuff I install in mine would be better in the `scripts/run_docker_build.sh` anyway.  (Specially for the conda-forge case, where it will be a way to self-document the dependencies that are not available on conda.)

**Pull request merged**
