### PR TITLE
Latest compliance-checker.

### PR DESCRIPTION
**Pull request by ocefpaf**
- Support for Windows through cf_units
- CI Travis Fixes
- Better GliderDAC compliance tests
- Better skip control for QC variables, now relies on 'flag_meanings' attribute.
- Fixes recursion bug
- Fixes horizontal grid check bug

### CODE REVIEW

**Comment by ocefpaf** [comment]
Ping!

@rsignell-usgs can you review and merge this one.

@abirger once this is merge can you test the Windows version?

**Comment by abirger** [comment]
@ocefpaf , sure thing. Waiting for @rsignell-usgs ...

**Comment by abirger** [comment]
@ocefpaf , sorry but no go:

```
C:\NOAA\IOOS\SOS-Compliance-Tester\CARA_test\netCDF files>activate compliance_checker
Activating environment "compliance_checker"...

[compliance_checker] C:\NOAA\IOOS\SOS-Compliance-Tester\CARA_test\netCDF files>compliance-checker --help
usage: compliance-checker-script.py [-h]
                                    [--test {gliderdac,acdd,cf,ioos} [{gliderdac,acdd,cf,ioos} ...]]
                                    [--criteria [{lenient,normal,strict}]]
                                    [--verbose]
                                    dataset_location

positional arguments:
  dataset_location      Defines the location of the dataset to be checked.

optional arguments:
  -h, --help            show this help message and exit
  --test {gliderdac,acdd,cf,ioos} [{gliderdac,acdd,cf,ioos} ...], -t {gliderdac,acdd,cf,ioos} [{gliderdac,acdd,cf,ioos} ...], --test= {gliderdac,acdd,cf,ioos} [
{gliderdac,acdd,cf,ioos} ...], -t= {gliderdac,acdd,cf,ioos} [{gliderdac,acdd,cf,ioos} ...]
                        Select the Checks you want to perform. Either all
                        (default), cf, ioos, or acdd.
  --criteria [{lenient,normal,strict}], -c [{lenient,normal,strict}]
                        Define the criteria for the checks. Either Strict,
                        Normal, or Lenient. Defaults to Normal.
  --verbose, -v         Increase output. May be specified up to three times.

[compliance_checker] C:\NOAA\IOOS\SOS-Compliance-Tester\CARA_test\netCDF files>compliance-checker --test=acdd Copy.nc
Running Compliance Checker on the dataset from: Copy.nc
Traceback (most recent call last):
  File "C:\Users\Alex Birger\Anaconda\envs\compliance_checker\Scripts\compliance-checker-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Users\Alex Birger\Anaconda\envs\compliance_checker\Scripts\cchecker.py", line 21, in main
    args.criteria)
  File "C:\Users\Alex Birger\Anaconda\envs\compliance_checker\lib\site-packages\compliance_checker\runner.py", line 42, in run_checker
    ds = cs.load_dataset(ds_loc)
  File "C:\Users\Alex Birger\Anaconda\envs\compliance_checker\lib\site-packages\compliance_checker\suite.py", line 343, in load_dataset
    xml_doc = ET.fromstring(str(doc))
  File "lxml.etree.pyx", line 3103, in lxml.etree.fromstring (src\lxml\lxml.etree.c:70569)
  File "parser.pxi", line 1828, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:106403)
  File "parser.pxi", line 1716, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:105194)
  File "parser.pxi", line 1086, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:99876)
  File "parser.pxi", line 580, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:94350)
  File "parser.pxi", line 690, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:95786)
  File "parser.pxi", line 620, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:94853)
lxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1

[compliance_checker] C:\NOAA\IOOS\SOS-Compliance-Tester\CARA_test\netCDF files>
```

**Comment by ocefpaf** [comment]
@abirger Can you get me a copy of that file so I can investigate it here?

I am also pining @lukecampbell since he is the CC expert.

**Comment by abirger** [comment]
@ocefpaf , no problem, sent it to you Gmail. BTW, the very same file was tested OK in Linux...

**Comment by ocefpaf** [comment]
Thanks!  I think it is unrelated to `udunits2`.  Maybe it is the `lxml` version... I will investigate once the file gets here.

**Comment by abirger** [comment]
It fails the same way with any file, even with the test ones that come with it. Perhaps something related to the windows/Linux difference in paths/notation/etc.?

**Comment by ocefpaf** [comment]
All I can say for now is that the Linux compliance-checker call does not fall into that if clause where Windows fails.  I will try this on Windows later and get to the bottom of what is going on.

**Comment by abirger** [comment]
Thanks!

**Comment by daf** [comment]
@ocefpaf @abirger can you email me a copy of the file as well?  use my gmail account please (on github page)

**Comment by daf** [comment]
Fixed in ioos/compliance-checker#118, build away!

**Comment by ocefpaf** [comment]
@daf Can we get a bugfix release? I want to avoid building from master.

**Comment by daf** [comment]
done, https://github.com/ioos/compliance-checker/releases/tag/1.1.1

**Comment by ocefpaf** [comment]
and done: https://github.com/ioos/conda-recipes/pull/250

Thanks!

**Comment by abirger** [comment]
YESSS, it works! @ocefpaf , @daf  - thanks a lot, it was very, very fast fix!

**Comment by ocefpaf** [comment]
> YESSS, it works! @ocefpaf , @daf - thanks a lot, it was very, very fast
fix!

Thanks for testing it out.

**Comment by abirger** [comment]
No problem. BTW, is there a way to run both ACDD and CF tests at one go? I tried various combinations of acdd and cf with the `--test=` attribute but nothing seems to work...

**Comment by daf** [comment]
The Python argument parser is supposed to handle these with ease, but I'm seeing a lot less flexibility on Windows than on Linux.  Will investigate.

**Comment by daf** [comment]
@abirger, managed to have some success using this form:
`python cchecker.py --test cf acdd -- <path_to_file>`

Can also use `--criteria normal` instead of the `--` syntax - if you don't have something else, the filename will get interpreted as another param to `--test` and it yells at you. 

I also don't think it will let you use the `=` versions.  Rather peculiar.

**Comment by abirger** [comment]
@daf , thanks, your suggestion works. Actually, isolation of the file name with `--criteria=normal` works as well as `--criteria normal`.

**Pull request merged**
