### PR TITLE
docs

### PR DESCRIPTION
**Pull request by ocefpaf**
This PR converts the wiki pages to actual docs hosted as `gh-pages` generated via `mkdocs`

You can see a rendered demo version at: http://ocefpaf.github.io/conda-recipes

Ping @bekozi and @jbosch-noaa.  This should make it easier to edit the docs in the future.

You will need:

```shell
pip install mkdocs
pip install markdown_checklist
pip install python-markdown-math
```

and check http://www.mkdocs.org/ for more instructions.

(Ironically none of those are available in the IOOS conda channel!)

### CODE REVIEW

**Comment by abirger** [comment]
@ocefpaf ,  @jbosch-noaa, Why use MkDocs for that? It will make the third web page generating tool in use along with Hugo and Pelican...

**Comment by ocefpaf** [comment]
@abirger I am just testing Mkdocs here because I am familiar with it.  I like its simplicity and the themes they ship. We can try Hugo too! Could you send a PR here so we can compare the two tools?

The choice for Pelican is a different problem though.  In the system-test blog we need a tool that parse the Jupyter Notebooks as pages HTML pages. I did not see a clear way to do that with Hugo. In fact I know only two tools for the job: pelican (actually the pelican notebook plugin) and [Nikola](https://getnikola.com/blog/).

If you know a way to convert the `.ipynb` notebook to Hugo pages let me know.

**Comment by abirger** [comment]
@ocefpaf , @jbosch-noaa, By no means I insist on using Hugo! It is the same for me as the MkDocs is for you - I just got used to it. I tried MkDocs as well but at that time it was just in embryo state, and could do almost nothing useful. I looked at Nicola too, and I was very impressed; the only thing that averted me from it was the need to install (and, of course, to know some Python), while Hugo was just a single executable. The Notebooks were not required at that moment, so Hugo was more or less obvious choice. We have to reconsider now, so maybe Nicola would be the right choice. Or Pelican for that matter.
Just FYI, I have not seen the notebook conversion tool for Hugo but there are at least 2 ways of automatic deployment to GitHub Pages for Hugo - with [Wercker](https://gohugo.io/tutorials/automated-deployments/) and [CodeShip](https://tinybot.io/post/codeship_hugo/). Although I have not tried any of them yet, the latter seems preferable, as the config process is very straightforward and simple, and the deployment script already exists.

**Comment by abirger** [comment]
@ocefpaf , you got me with the PR. It's not my cup of tea at all; I do not have any code to submit...

**Comment by ocefpaf** [comment]
> @ocefpaf , you got me with the PR. It's not my cup of tea at all; I do not have any code to submit...

No problem.  I will test Hugo here and see how it goes.  I will keep you in the loop.

**Comment by abirger** [comment]
@ocefpaf , there is a [GitHub Pages deployment with Hugo](http://ioos.github.io/website_deployment_workflow_updated/) workflow, that may help. Or, I can get the markdown Wiki pages and compile a demo site with Hugo.

**Comment by ocefpaf** [comment]
Awesome!  That would be nice.

**Comment by abirger** [comment]
OK, will do it tomorrow.

**Comment by abirger** [comment]
@ocefpaf , @jbosch-noaa, you may check a Hugo demo version at http://abirger.github.io/conda-recipes/ . Unfortunately, Hugo (unlike MkDocs, I presume) requires some (actually, pretty many) files and directories to be held on `master` branch in order to properly render the web site. @ocefpaf , you will see the difference if you compare my fork and IOOS original repo. Hopefully, the automation via  [Wercker](https://gohugo.io/tutorials/automated-deployments/) or [CodeShip](https://tinybot.io/post/codeship_hugo/) allows to get rid of these files but it has to be checked.

**Comment by ocefpaf** [comment]
> @ocefpaf , @jbosch-noaa, you may check a Hugo demo version at http://abirger.github.io/conda-recipes/

Thanks!

> Unfortunately, Hugo (unlike MkDocs, I presume) requires some (actually, pretty many) files and directories to be held on master branch in order to properly render the web site.

The boilerplate isn't that bad but I agree, `mkdocs` is cleaner.

> Hopefully, the automation via Wercker or CodeShip allows to get rid of these files but it has to be checked.

I think that the theme colors and fonts you have there suits nicely to IOOS, but I don't like the 1-page summarize navigation.  That makes our documentation look sequential blog posts.

Is there a way to changed the layout to tabs? Another option would be to tweak the `mkdocs` theme to look like the page you generated.

**Comment by abirger** [comment]
@ocefpaf , sorry but with the chosen theme there is no way to use tabs without serious theme modification. However, it is possible to get rid of those summaries on the 1st page altogether. Check http://abirger.github.io/conda-recipes/ now - I made the first page similar to what you had with Wiki and MkDocs site.

I played a little with Nikola but have not moved too far. While it feels way more flexible than Hugo, it's configuration is more complex, and the themes are quite limited. It has a much longer learning curve than Hugo but I believe it's doable.

BTW, the MkDocs' `readthedocs` built-in theme seems to have a similar layout to the Hugo's `lanyon` that I use for the IOOS Doc sites. Could you please redress your demo site into that theme to see how close it will be?

**Comment by ocefpaf** [comment]
> @ocefpaf, sorry but with the chosen theme there is no way to use tabs without serious theme modification. 

Not big deal.  I think this is good and we are slowly understanding the strengths and weakness of our tools. (I wish I had this talk with you earlier :grimacing:)

> I played a little with Nikola but have not moved too far.

Nikola is an alternative to Pelican when it comes to notebook parsing.  I would not worry too much about that because our Pelican solution is working. (I have high expectations about nbshpinx. It is a Sphinx extension that parses the notebooks too. But that is something for the future...)

> Could you please redress your demo site into that theme to see how close it will be?

Yes. That is the next natural step in our experimentes.  It will take me some time though. I am a little bit swamped right now.

BTW If that looks good would you be willing to try it out in the other repos?  Once the theme is done it is mostly a copy-and-paste operation. (The Markdown files might need some minor modifications.)

Thanks @abirger!  This is helping a lot to sort things out!!

**Comment by abirger** [comment]
> BTW If that looks good would you be willing to try it out in the other repos? 

Sure thing! As I said, I chose Hugo over MkDocs only because at that moment Hugo allowed me to do more, while still keeping it simple. I see that MkDocs has progressed well since then, and it offers some nice features now that Hugo still does not. And Hugo has always been very blog-oriented tool, so although non-blog sites are possible, they take some juggling and workaround.

**Comment by ocefpaf** [comment]
OK.  I will work on the theme tweaking and I'll get back to you.  (I will be away next week.  Going to the US for a conference, but I will prioritize this once I am back.)

**Comment by abirger** [comment]
Take your time. I guess that this is not number 1 priority. Meanwhile I will delve into MkDocs...

**Comment by ocefpaf** [comment]
> Take your time. I guess that this is not number 1 priority.

Not really. I want to get his sorted out as soon as possible. BTW I made a quick test with the `readthedocs` theme and some minor tweaks:

http://ocefpaf.github.io/conda-recipes/

There is a long way to go to make it look more like your page, but we'll get there.

> Meanwhile I will delve into MkDocs...

Let me know if you have any questions.

**Comment by abirger** [comment]
@ocefpaf , even with the "long way to go", the `readthedocs` looks very good. Just need to figure out the sliding sidebar (to free space on the page for document), colors, and some other small details, and it will be better than I have now for IOOS docs.

**Comment by ocefpaf** [comment]
I will work on styling for the other pages but due to the move to conda-forge we won't need docs here.

**Pull request closed without merging**
