### PR TITLE
Using lazy_dtype branch (again).

### PR DESCRIPTION
**Pull request by ocefpaf**
Using `iris` and `biggus` from @rhattersley branch.  This is a workaround until https://github.com/SciTools/iris/pull/1560 get merged.

### CODE REVIEW

**Comment by ocefpaf** [comment]
Pyke did not had a build number and somehow did not get build for Linx32.

**Comment by ocefpaf** [comment]
@rsignell-usgs Do not merge this yet!  I am testing all the moving parts here to make sure it will work.

**Comment by ocefpaf** [comment]
@rsignell-usgs it is safe to merge now.

**Comment by rsignell-usgs** [comment]
we should also modify the requirements files to reflect this iris version change, no?

**Comment by ocefpaf** [comment]
Yes, let me do it in this PR.  Hold on.

**Comment by ocefpaf** [comment]
Done.  I did not touch the `ioos_req_exact_mac_{osx,win64}.txt` files since those will get stale very quickly.

**Pull request merged**
