### PR TITLE
Our WinGCC issues are history!

### PR DESCRIPTION
**Pull request by ocefpaf**
I did not test any of the Fortran compiled modules.  Hope that @rsignell-usgs can do that on his Windows machine.

### CODE REVIEW

**Comment by ocefpaf** [comment]
@rsignell-usgs do not merge this one yet.  I am still testing a few things...

**Comment by rsignell-usgs** [comment]
@ocefpaf , what's the best way for me to test on windows?    Where do I get the binaries built by the PR?

**Comment by ocefpaf** [comment]
Let me just fix AppVeyor and we'll merge this (almost there). That way we will see how conda will solve the dependencies in a "real-live" situation (the channel set, etc).

**Comment by ocefpaf** [comment]
@rsignell-usgs I removed `cartopy` (and `iris`) from this PR and everything else built just fine.  Including `octant` with `mingwpy`.  I will merge this to get the packages uploaded and I will fix `cartopy` in another PR.

**Comment by rsignell-usgs** [comment]
@hetland, does this notebook https://github.com/hetland/octant/blob/master/octant_examples.ipynb
test any of the Fortran modules?

**Comment by rsignell-usgs** [comment]
Actually, I'm pretty sure the answer is yes, because isoslice calls a method of iso, which is Fortran.
https://github.com/hetland/octant/blob/master/octant/tools.py#L159
https://github.com/hetland/octant/blob/master/octant/tools.py#L13
https://github.com/hetland/octant/blob/master/octant/src/iso.f

And if that's the case, @ocefpaf, here's Rob's notebook 
https://github.com/hetland/octant/blob/master/octant_examples.ipynb
running on win32 after installing octant (and matplotlib, basemap and netcdf4):
8-28-2015 3-20-05 pm

Woo hoo!   That's been a long time in the works!   Congrats! :tada: :tada: :tada:

**Comment by ocefpaf** [comment]
Win64 is coming in the next PR.

PS: Thanks my to mom's computer and the lack of distraction from my own laptop :wink:   The only thing I could do here  was to read `mingwpy` docs.

**Comment by rsignell-usgs** [comment]
@ocefpaf, well, thank your mom for me! ;-)

**Pull request merged**
