### PR TITLE
Using travis-ci to build OSX only

### PR DESCRIPTION
**Pull request by ocefpaf**
@rsignell-usgs This PR implements the changes we discussed via e-mail.

Note that this will disable the Linux builds!  I will be updating the Linux binaries manually using @pelson's docker images until we get `circle-ci` working.

### CODE REVIEW

**Comment by pelson** [comment]
Makes sense. The circle-ci builds aren't too far away. :wink:

**Comment by ocefpaf** [comment]
Looking forward to see what you are brewing in https://github.com/conda-forge!

Meanwhile this change makes sense even without `circle-ci`.  Our builds are fragmented now: this repo builds Windows and Modern Linux,  another [repo](https://github.com/pyoceans/conda-recipes-pyoceans) for OSX, and a manual build for RHEL6 (that is hosted in another binstar channel :scream:)!

To solve that fragmentation we will be deleting the RHEL6 binstar channel.  Performing 1 "manual" build for Linux (RHEL compatible) and use the CIs for Windows and OSX.

1 repository and 1  binstar channel to rule them all and in the cloud bind them!

**Comment by ocefpaf** [comment]
(Oops, I paste the message in the wrong tab before!)

**Comment by rsignell-usgs** [comment]
Fingers crossed!  :grin:

**Comment by ocefpaf** [comment]
@rsignell-usgs The next PR will seem massive, but it just updates the build number on all packages.  This is needed to get a new Linux RHEL-compat build for them.  (In theory we do not need to rebuild the pure python modules, but it is easier that way :wink:)

I will build them locally and upload to binstar using our token.  Once all builds are successful I will send the PR with the changes.

**Comment by rsignell-usgs** [comment]
Got it.   I'm looking forward to shutting down the RHEL6 channel!

**Pull request merged**
