### PR TITLE
Added pymatbridge.

### PR DESCRIPTION
**Pull request by ocefpaf**
@rsignell-usgs I have only one notebook that calls matlab :grin:, but I believe this might be important for other cases.

### CODE REVIEW

**Comment by rsignell-usgs** [comment]
@ocefpaf , I agree.    We have a lot of matlab users, and this should be useful.

**Comment by ocefpaf** [comment]
Latest master fixes pymatbridge for win64, but it is not available for win32.  I will modify the recipe to pull from master.  Do not merge it yet.

**Comment by rsignell-usgs** [comment]
Just as a reminder, the reason we still want the 32-bit windows binaries is to interface with python-based apps like ESRI 32-bit ArcMap.

**Comment by ocefpaf** [comment]
Don't worry, I will not remove our win32 build on pymatbridge account :smile:

**Comment by rsignell-usgs** [comment]
@ocefpaf , strange.  We expected the 32bit to fail, right?  But the 64-bit is failing too, with an error saying that pymatbridge doesn't work on *32 bit*:
https://ci.appveyor.com/project/comtbot/conda-recipes/build/1.0.114/job/0hu61er5fqcggkox#L984

**Comment by ocefpaf** [comment]
(I think you missed my message above :wink:)

> Latest master fixes pymatbridge for win64

This is a bug in `pymatbridge` that is fixed latest master, I just need to point our recipe to it.  (In fact, doing it now.)

**Comment by rsignell-usgs** [comment]
@ocefpaf ,  I saw your message.   I just thought that was already modified.   I should have looked at the meta.yaml!

**Comment by ocefpaf** [comment]
@rsignell-usgs is should be good to go now.  Sorry it took so long for a simple thing.  I am :sleeping:  today.

**Pull request merged**
