### PR TITLE
Update flopy version

### PR DESCRIPTION
**Pull request by jdhughes-usgs**

### CODE REVIEW

**Comment by ocefpaf** [comment]
@jdhughes-usgs pandas is used but it is not in the dependency list:

https://github.com/modflowpy/flopy/blob/master/setup.py#L34

Can you updated the recipe to install pandas too?

PS: Note that importing the module at build time (https://github.com/modflowpy/flopy/blob/master/setup.py#L8) forces all the dependencies to be available before they are actually needed.  Prefer a pattern like [this](https://github.com/pyoceans/python-ctd/blob/master/setup.py#L19-L30) to inject the version number in the `setup.py`.

**Comment by ocefpaf** [comment]
@jdhughes-usgs there is no need for #358, we can re-start this PR once you re-issue the 3.2.2 tag.

**Comment by jdhughes-usgs** [comment]
Reissued 3.2.2 tag. Still getting used to requests. Sorry.

**Comment by ocefpaf** [comment]
> Reissued 3.2.2 tag. Still getting used to requests. Sorry.

No problem.  The CIs are doing their thing and the PR will be ready in a few minutes.

**Pull request merged**
