### PR TITLE
Testing latest shapely.

### PR DESCRIPTION
**Pull request by ocefpaf**
**Do not merge!**

Just testing latest shapely...

### CODE REVIEW

**Comment by ocefpaf** [comment]
We probably need to update the Windows patch.

**Comment by ocefpaf** [comment]
Both Shapely and Pyresample (  #261 ) are tripping due to the lack of `stdint.h'` in Visual Studio.

`fatal error C1083: Cannot open include file: 'stdint.h': No such file or directory`

There are a few workarounds for this issues.  I will investigate which one serves us best.

**Comment by rsignell-usgs** [comment]
Dang it.  What a pain!

**Comment by ocefpaf** [comment]
Actually, after SciPy, I am positive that the default channel will provide
a decent shapely. Soon we will be deprecating ours.

**Pull request closed without merging**
