### PR TITLE
Added django-extensions.

### PR DESCRIPTION
**Pull request by ocefpaf**
This PR adds the last missing sci-wms dependency listed in `requirements.txt`, `requirements-dev.txt`, and `requirements-prod.txt`.

@kwilcox let me know if there is anything else you need.  I would like to have all the dependencies on the IOOS channel to make it easier for future users.

### CODE REVIEW

**Comment by rsignell-usgs** [comment]
@kwilcox, ping?

**Comment by kwilcox** [comment]
* django-grappelli
* django-typed-models
* dj-static

**Comment by ocefpaf** [comment]
Thanks @kwilcox!

@rsignell-usgs I will add those here so hold off merging for a while...

**Comment by rsignell-usgs** [comment]
@ocefpaf, ready now?

**Comment by ocefpaf** [comment]
Not yet...

**Comment by ocefpaf** [comment]
Phew!  Now it is!

Note to self: Some of the `django.<something>` return a `django.core.exceptions.ImproperlyConfigured`, but I think that is OK.  Only with a proper configured env this will go away.  (Maybe I should test that in the sci-wms metapackage...)

**Pull request merged**
