### PR TITLE
Sci-wms repo and recipe update.

### LINKED ISSUE #173: Which repository should we use for sci-wms?
https://github.com/kwilcox/sci-wms.git or https://github.com/sci-wms/sci-wms

### PR DESCRIPTION
**Pull request by ocefpaf**
This PR closes #173.

@rsignell-usgs and @kwilcox I would like to:
- [ ] Write a script to "copy" `sci-wms` to a working directory and drop the name  `sci-wms-deps`
- [ ] Run a test on that working directory (like: `python manage.py test`).

What do you think?  Worth pursuing? This script would be something like `sci-wms [new|deploy|help|serve]` format.

### CODE REVIEW

**Comment by rsignell-usgs** [comment]
Andrew (@ayan-usgs) or Chris (@cbcunc), can you respond to Filipe (@ocefpaf)?    
@kwilcox is going to be gone for a few weeks (baby #3) and I'm not really qualified to answer.

**Comment by ocefpaf** [comment]
The Windows failure is because `setproctitle` needs a C compiler.  I will disable it on windows for now until we have #185 working.

**Comment by rsignell-usgs** [comment]
@ocefpaf, having sci-wms on windows is not a high-priority (although I think @ayan-usgs is running sci-wms on windows)

**Comment by ocefpaf** [comment]
This will not disable `sci-wms` on windows.  It is only the `setproctitle` dependency that will not be satisfied.   (I am not a user to say what will be the side effects of that.)

**Comment by ayan-usgs** [comment]
@rsignell-usgs  and @ocefpaf,

I was unable to install setproctitle in a Python 2.7 virtual environment using Visual Studio 2008. However, in reference to #185, I found that the install does work  when using mingw32 as the compiler. 

I've had good success with mingw32 for awhile now, though with the caveat that some packages from pypi can be installed using VS 2008 or mingw32, while others can't. I still find myself periodically going to http://www.lfd.uci.edu/~gohlke/pythonlibs/ to find a wheel or an executable for those times where it's not worth fighting with Windows.

**Comment by ocefpaf** [comment]
> I found that the install does work when using mingw32 as the compiler.

Good to know!  I am working to get this going in our AppVeyor setup.

Another question: is `setproctitle` a mandatory or optional dependency for sci-wms?  (The current docs seems to be outdated and it is hard to know the details.)

**Comment by rsignell-usgs** [comment]
@ocefpaf good to go on this, or wait?

**Comment by ocefpaf** [comment]
If `setproctitle` is optional we are good to go.  But the docs are unclear about that...

**Comment by ayan-usgs** [comment]
@ocefpaf,

'setproctitle' is not actually needed to run sci-wms.

**Comment by ocefpaf** [comment]
OK, I got it from here:

https://github.com/sci-wms/sci-wms/blob/master/requirements-prod.txt#L2

@rsignell-usgs this PR is good to go then.

**Pull request merged**
