### PR TITLE
adding pygc

### PR DESCRIPTION
**Pull request by rsignell-usgs**
pygc is a great circle calculation package, a requirement for modflow2netcdf

### CODE REVIEW

**Comment by ocefpaf** [comment]
@kwilcox Was this code part of paegan?

**Comment by kwilcox** [comment]
Yeah I split it off some time ago from https://github.com/axiom-data-science/paegan/blob/master/paegan/external/greatcircle.py but paegan hasn't been updated to use this instead of the built-in stuff.

**Comment by ocefpaf** [comment]
Awesome.  I am all for small self contained modules.

**Comment by pelson** [comment]
Interesting timing. I merged this today into cartopy: https://github.com/SciTools/cartopy/blob/master/lib/cartopy/geodesic/_geodesic.pyx

**Comment by ocefpaf** [comment]
> Interesting timing. I merged this today into cartopy:

Which I was going to suggest a separate module but forgot to write it there...

**Comment by pelson** [comment]
> Which I was going to suggest a separate module but forgot to write it there...

I completely buy the small packages thing, but there is a lot of machinery that you have to duplicate when dealing with external C deps (such as you do with Proj.4) which made it less appealing. The pure python implementation is cool though!

**Pull request merged**
