### PR TITLE
Bump the build number for clean Linux/OSX binaries

### PR DESCRIPTION
**Pull request by ocefpaf**
@rsignell-usgs Do not merge this one yet.  Most of this PR are the build number "bumps" I had to do to get a complete Linux re-build.

I was thinking that, since the channel has  OSX binaries from 3 different machines (Chris Barker, Rusty, and Travis), maybe it is good to test a complete re-build for OSX too.

AppVeyor will  crash due to time limit, but we can ignore that.

### CODE REVIEW

**Comment by rsignell-usgs** [comment]
Okay, should I wait for clean linux binaries also before testing them on the comt platform?

**Comment by ocefpaf** [comment]
Nope, the Linux binaries are already there.  Go ahead and let me know if they work for you.  (I sent you an e-mail about it.)

**Comment by ocefpaf** [comment]
I am not sure why conda is pulling up geos 3.3.3 instead of ours (3.4.2), but that is breaking cartopy.

**Comment by rsignell-usgs** [comment]
The linux version on binstar is working fine though, right?

**Comment by ocefpaf** [comment]
The right answer is yes an no.  The Linux builds are also pulling geos 3.3.3, but the crash only happens on  OSX.  Linux cartopy works just fine.  (See issue https://github.com/SciTools/cartopy/issues/612)

**Comment by ocefpaf** [comment]
@rsignell-usgs My guess is that geos 3.3.3 is from basemap.  We have a few packages that are pulling basemap (octant and sci-wms).

One solution would be to stop using basemap from the default channel and provide one with geos 3.4.2.  However, conda should be smart enough to update geos.  (Unless their basemap package is pinned the geos version.)

**Comment by rsignell-usgs** [comment]
Interesting. Ideally we would get rid of basemap in favor of cartopy. I know that basemap is in the process of being dropped my sci-wms and I'm not sure how much octant needs it.

**Comment by ocefpaf** [comment]
@rsignell-usgs This is failing due to time-out, but after #216 and #215 are merged this PR should  be OK.  After the merge I can keep "re-starting" travis and AppVeyor to get all the packages built and uploaded.

**Comment by shoyer** [comment]
I think you need to rebuild basemap to get it to work with geos 3.4.2 (needed for cartopy). The good news is that the recipe is not very complicated: https://github.com/TheClimateCorporation/conda-recipes/blob/master/basemap/meta.yaml

**Comment by ocefpaf** [comment]
Thanks @shoyer I actually already have that in there: https://github.com/ocefpaf/conda-recipes/blob/Linux_builds/basemap/meta.yaml#L16

This PR is massive and ill formed.  I needed it to re-build all the Linux64 binaries using a docker  image.  the right thing to do would be to wipe the binaries from the channel and start over, but I do not want to loose the download statistics so I bumped all the build numbers.

The current failure is due to travis and AppVeyor timing-out.  Things are consistent with geos-3.4.2 now.  and this PR is safe to be merged.

BTW: The  main issue was not basmap, it was the default anaconda shapely. (See #216.)

**Comment by rsignell-usgs** [comment]
@ocefpaf , this one can't be automatically merged.

**Comment by ocefpaf** [comment]
@rsignell-usgs rebased and ready to go.  We can wait for travis, but it will probably time-out again.

**Comment by rsignell-usgs** [comment]
Merging because errors are just timeouts

**Comment by rsignell-usgs** [comment]
Interesting. Pull requests with failing status can't be merged from a phone!

**Comment by ocefpaf** [comment]
I will keep "re-starting" Travis and AppVeyor once this PR lands on `master`.  Every re-start it will take less time because the packages **are** uploaded after the merge.

PS: In the future we should avoid doing something like this again.  It is preferable to bump every package in a separate PR.

**Comment by ocefpaf** [comment]
Let me try then...  Done!

**Pull request merged**
