### PR TITLE
Create `.travis.yml`.

### PR DESCRIPTION
**Pull request by ocefpaf**
@rsignell-usgs We need to activate travis for this repository (https://travis-ci.org/profile/ioos) to see if this works.  I do not have admin rights to do it.

### CODE REVIEW

**Comment by ocefpaf** [comment]
BTW **DO NOT MERGE!**  It is likely that this will fail.  Lets use this PR to keep updating/fixing the yaml file until we get it right and only then merge.

**Comment by rsignell-usgs** [comment]
Like this, right?
2-12-2015 2-06-47 pm

**Comment by ocefpaf** [comment]
Yes, and now travis-ci is working its magic...

**Comment by rsignell-usgs** [comment]
oh no!
OSError: liblas_c.so: cannot open shared object file: No such file or directory

**Comment by ocefpaf** [comment]
... and we have out first error!

**Comment by ocefpaf** [comment]
libLAS (python) depends on libLAS (C and C++) the conda package for the C/C++ is missing.  You probably can do a local built because you have it there (I just checked that, like travis, I cannot.)

PS:  Who gives the library and the wrapper with the same name?

**Comment by ocefpaf** [comment]
I found that "https://github.com/grantbrown/laspy" an alternative to libLAS (python wrapper).  It seems to be better maintained (shows recent activity in Nov 2014) and it is better named.  LibLAS latest version is from 2011:

https://pypi.python.org/pypi/libLAS

@rsignell-usgs Question:

1. Rename libLAS (python wrapper) to make room for libLAS (C/C++)?
2. Rename libLAS (C/C++) to something else and keep libLAS (python wrapper) ?
3.  Delete libLAS (python wrapper) add libLAS (C/C++)  and laspy?

**Pull request merged**
