### PR TITLE
Bug fix release

### PR DESCRIPTION
**Pull request by ocefpaf**
# 1.1.1 Windows Bug Fix

### CODE REVIEW

**Comment by abirger** [comment]
@ocefpaf , and how can I get this fix? `conda update` does not know about it yet:
```
[compliance_checker] C:\Users\Alex Birger\Documents\GitHub\compliance-checker>conda update compliance-checker
Fetching package metadata: ......
# All requested packages already installed.
# packages in environment at C:\Users\Alex Birger\Anaconda\envs\compliance_checker:
#
compliance-checker        1.1.0                    py27_0
```

**Comment by ocefpaf** [comment]
We need to wait from @rsignell-usgs to merge it...  but since he is flying back home I will break the "no self-merges" rule.  But be cool and do not tell Rich :sunglasses:

**Comment by ocefpaf** [comment]
PS: It take a few minutes until the files show up on binstar.  You can follow the build here:

https://ci.appveyor.com/project/comtbot/conda-recipes

**Comment by abirger** [comment]
@ocefpaf , Sorry for making you break the rule... my lips are sealed...

**Pull request merged**
