### PR TITLE
Fixed geolinks

### PR DESCRIPTION
**Pull request by ocefpaf**
@rsignell-usgs this is not an updated!  The metadata seemed to be from another package (version, URL, etc).  Can you review if this is the right package?

### CODE REVIEW

**Comment by rsignell-usgs** [comment]
Yes, this is the right package, but requesting a release here:
https://github.com/geopython/geolinks/issues/1

**Comment by ocefpaf** [comment]
> but requesting a release

Lets put this PR on hold then.

**Comment by rsignell-usgs** [comment]
Actually, I guess since @tomkralidis has a versioned pypi package, we don't need the tagged github release.

**Comment by ocefpaf** [comment]
I am OK with it. :+1:

**Comment by tomkralidis** [comment]
https://github.com/geopython/geolinks/issues/1#issuecomment-89465686



FYI we had 0.0.1 in PyPI, and there have some (minor) changes since then, but no tag.

For good measure I have cut a 0.1.0 release tag and updated PyPI as well.

**Pull request merged**
