### PR TITLE
Bump pyaxiom to 1.1.6 (bugfixes)

### PR DESCRIPTION
**Pull request by kwilcox**

### CODE REVIEW

**Comment by kwilcox** [comment]
Failing on CircleCI due to this bug which was fixed 5 days ago: https://github.com/pelson/Obvious-CI/commit/bf13dba1b5e07767913921d8947e07577b8ce015

**Comment by ocefpaf** [comment]
> Failing on CircleCI due to this bug which was fixed 5 days ago:
pelson/Obvious-CI@bf13dba

Kyle, my laptop just died and I won't be able to fix this tomorrow. I will
try to borrow one and check this ASAP.

**Comment by kwilcox** [comment]
No rush, pushed to another anaconda org until it's available in IOOS!

**Comment by ocefpaf** [comment]
Merging this.  #735 should fix it.

**Pull request merged**
