### PR TITLE
uhdas

### PR DESCRIPTION
**Pull request by ocefpaf**
`uhdas` is imported when running `quick_adcp.py`

Ping @efiring.

### CODE REVIEW

**Comment by efiring** [comment]
Please do not make a conda package for uhdas.  It is not yet appropriate.  The import in pycurrents is a bug.  I will fix it there.

**Comment by ocefpaf** [comment]
No problem.  I am just testing the build.  I won't merge it and no package will be created.

**Comment by efiring** [comment]
A full build actually would require running "make install" in serial_c.  The logging is done using independent processes compiled from C.

**Comment by ocefpaf** [comment]
Thanks.  Once you think `uhdas` is ready to be package I will try to do that.

I wanted to check what was needed to satisfy the missing import (`uhdas.uhdas.rdi_setup`) in `quick_adcp.py`.  Since that is a bug there is no need to get this on the channel yet.

**Comment by efiring** [comment]
I think I have gotten rid of the uhdas imports:
http://currents.soest.hawaii.edu/hgstage/pycurrents/rev/2edadd32abdf

**Comment by ocefpaf** [comment]
There are a few other places [here](http://currents.soest.hawaii.edu/hgstage/pycurrents/file/2edadd32abdf/adcp/uhdasconfig.py#l28) that still imports `uhdas`.

**Comment by efiring** [comment]
http://currents.soest.hawaii.edu/hgstage/pycurrents/rev/bcc0b5fca3c0 fixes that one...

**Comment by ocefpaf** [comment]
Thanks.  I also removed the mercurial dependency to test the build on Windows+Python3.

See https://github.com/ocefpaf/conda-recipes/commit/d7817650d0243ef4b7b53c9c4e66677462e8c441 for the patch and https://ci.appveyor.com/project/comtbot/conda-recipes/build/1.0.1860 for the results.

**Comment by efiring** [comment]
On 2016/02/08 10:54 AM, Filipe wrote:
> Thanks. I also removed the mercurial dependency to test the build on
> Windows+Python3.

The build system is supposed to work now with or without finding hg, so 
if it does not, that is a bug I would like to fix.

**Pull request closed without merging**
