### PR TITLE
Biggus update+win build

### PR DESCRIPTION
**Pull request by ocefpaf**
- Updated biggus
- Added windows build

### CODE REVIEW

**Comment by rsignell-usgs** [comment]
Why no travis here?

**Comment by ocefpaf** [comment]
@rsignell-usgs this PR could not be merged due to a conflict.  Now that I've rebased travis should be back.

**Comment by ocefpaf** [comment]
... Or not.  Sourceforge is down and travis cannot download boost 1.55

**Comment by rsignell-usgs** [comment]
Grrr.. When Travis fails because of intermittent issues like this, what do you do?  Just resubmit the PR every so often?

**Comment by ocefpaf** [comment]
We can restart travis using the web interface:

https://travis-ci.org/ioos/conda-recipes/builds/50885908

The first button on the right below "Settings."

**Comment by ocefpaf** [comment]
Closing (incorporate into #55).

**Pull request closed without merging**
