### PR TITLE
Clean meta

### PR DESCRIPTION
**Pull request by ocefpaf**
Resetting the build number is import to control the build of same version packages.

### CODE REVIEW

**Comment by rsignell-usgs** [comment]
Need to install swig?

**Comment by rsignell-usgs** [comment]
Ah, you beat me!

**Comment by ocefpaf** [comment]
If you merge #55 and #50 I will rebase this one and (Hopefully) be done with linux!  Then the real pain begins... AppVeyor and windows....

**Comment by ocefpaf** [comment]
Rebased... Lets wait for travis now.

**Comment by ocefpaf** [comment]
@rsignell-usgs Our first "full" successful travis run!  Once this gets merge the IOOS channel will finally be populated with the Linux binaries!! :fireworks: :tada: :crocodile: in :space_invader:

**Comment by rsignell-usgs** [comment]
Filipe, this is awesome!   Stuff like this is unheralded and often thankless, but is fundamental if we want workflows, applications and tools build on the IOOS infrastructure to be reproducible and widely used.

**Pull request merged**
