### PR TITLE
Testing latest udunits2 on windows.

### PR DESCRIPTION
**Pull request by ocefpaf**
2.2.18	2015-02-04T17:52:02-0700

- Eliminated the use of `unistd.h` on Windows.
- Improved support for static builds (i.e., builds that don't produce a sharable library).

Units Database:
- Corrected the definition of "dram" and added "fluid_dram".
- Changed the definition of "molecule" to "1/avogadro_constant".
- Added comments and human-readable definitions.

Program:
- Removed latent bug on Windows in determining the name of the program.

Misc:
- Removed lint discovered by Coverity.

### CODE REVIEW

**Comment by rsignell-usgs** [comment]
@ocefpaf, still some windows problems, I guess?
```
CMake Error at lib/CMakeLists.txt:44 (add_library):
Cannot find source file:
 
tsearch.c
 
Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
.hxx .in .txx
 
 
CMake Error at prog/CMakeLists.txt:19 (add_executable):
Cannot find source file:
 
XGetOpt.c
 
Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
.hxx .in .txx
 
 
CMake Error: CMake can not determine linker language for target: libudunits2 
CMake Error: Cannot determine link language for target "libudunits2". 
CMake Error: CMake can not determine linker language for target: udunits2 
CMake Error: Cannot determine link language for target "udunits2". 
-- Generating done
-- Build files have been written to: C:/conda/conda-bld/work/udunits-2.2.18/build
 
C:\conda\conda-bld\work\udunits-2.2.18\build>nmake libudunits2 || exit 1
 
Microsoft (R) Program Maintenance Utility Version 9.00.30729.01
Copyright (C) Microsoft Corporation. All rights reserved.
 
Scanning dependencies of target libudunits2
NMAKE : fatal error U1073: don't know how to make 'lib\CMakeFiles\libudunits2.dir\build'
```

**Comment by ocefpaf** [comment]
Yes, don't merge this yet.  I am just playing with the options (using AppVeyor as my windows box :wink:)

**Comment by ocefpaf** [comment]
OK, the first error is a missing file `/lib/tsearch.c` that is present on 2.2.17 and absent in 2.2.18.  I will check the github commits to understand why this is not there in the new version.

**Comment by ocefpaf** [comment]
Aha!  It is not in the tarball release, but it is in the repository!  Go figure...

"https://github.com/Unidata/UDUNITS-2/blob/master/lib/tsearch.c"

**Comment by ocefpaf** [comment]
End of experiment!

@rsignell-usgs The udunits "official" tarball for 2.2.18 is not Windows friendly.  Somehow `tsearch.c` got lost in the process of making the release.  The GitHub release for 2.2.17, or the latest master, works just fine.

I do not recommend updating our recipes to `master` and, if we want 2.2.18, we have to work with unidata to get this anomaly in the releases straighten out.

**Pull request closed without merging**
