### PR TITLE
Update pyaxiom to 0.11

### PR DESCRIPTION
**Pull request by rsignell-usgs**

### CODE REVIEW

**Comment by rsignell-usgs** [comment]
@ocefpaf , I don't understand the build issue on windows.   Something about SSL?  It seems that pyaxiom on windows worked with v 0.10

**Comment by rsignell-usgs** [comment]
@ocepaf, do you have to manually kick off the linux build?

**Comment by ocefpaf** [comment]
AppVeyor had some major updates that broke "git clone." (See #252 for example.)  I will try to fix it before merging this PR.  However, I will build and upload the Linux build, so we will miss the Windows and OSX only until I fix that.

**Comment by rsignell-usgs** [comment]
@ocefpaf , sheesh.   These problems suck.
Would it be worth looking at the Continuum build service again?  
Or does it still exist?   I went looking and couldn't find it, but did find these Continuum instructions on Travis and AppVeyor
http://conda.pydata.org/docs/travis.html
which made me wonder...

**Comment by ocefpaf** [comment]
If Continuum service got better they would have advertise it.  Also, they never had Windows support anyways.  We are stuck with AppVeyor for that.

BTW the changes are not all bad, some good stuff got into AppVeyor that will make our job easier.

http://www.appveyor.com/updates

**Comment by rsignell-usgs** [comment]
@ocefpaf , so should I see the new linux version here?
https://binstar.org/IOOS/pyaxiom/files

**Comment by ocefpaf** [comment]
Not yet... I am installing and configuring docker on my new machine.  It will take a few more minutes.  Hold on...

**Comment by ocefpaf** [comment]
... and done!  https://binstar.org/ioos/pyaxiom

**Pull request merged**
