### PR TITLE
Work around until new obvious-ci release

### PR DESCRIPTION
**Pull request by ocefpaf**
Or until we move to conda-build-all :wink:

### CODE REVIEW

**Comment by pelson** [comment]
What was the problem @ocefpaf ?

**Comment by ocefpaf** [comment]
The `.iteritems` fix did not make into the latest release. See #734 

PS: I would prep the release and update the conda-forge package, but my laptop is fried and I am sending this PR from my phone.  It is hard to type in this tiny screen!

**Comment by ocefpaf** [comment]
(But the GitHub mobile interface is awesome!)

**Comment by pelson** [comment]
Your using py3k with ObviousCI then? It takes very little effort to release an obvious-ci if that would be helpful. Else, we can work together on getting conda-build-all doing its thing?

**Comment by ocefpaf** [comment]
> Your using py3k with ObviousCI then?

Yeah... I changed everything to Python 3 after those annoying conda-build encoding bugs.  I guess they are all squashed now (or not https://github.com/conda/conda-build/issues/733).

> It takes very little effort to release an obvious-ci if that would be helpful. Else, we can work together on getting conda-build-all doing its thing?

I'd rather focus on `conda-build-all`.  I am OK downgrading to Python 2 or use `obvious-ci 0.5.0` for a while.  I will get my hands on a temporary laptop next week and I will start testing `conda-build-all`.

**Comment by pelson** [comment]
I have cut and built v0.6.1 of ObviousCI. Should solve the issue. Thanks @ocefpaf

**Comment by ocefpaf** [comment]
Thanks @pelson!

**Pull request merged**
