### PR TITLE
Added ioos_qartod

### PR DESCRIPTION
**Pull request by ocefpaf**
@lukecampbell Can I try to sell you `cf_units` instead of `quantities` here?

### CODE REVIEW

**Comment by rsignell-usgs** [comment]
@ocefpaf , merge this, or waiting to hear from @lukecampbell?

**Comment by ocefpaf** [comment]
This is good to merge.  We are pointing to release 0.0.2 that @lukecampbell issued during the meeting.

**Comment by ocefpaf** [comment]
@rsignell-usgs ping.

**Comment by lukecampbell** [comment]
Go ahead with this release, I've got HUGE changes in the pipeline for QARTOD (although most of them are on the CBIBS backend so you won't see them), I'll rope in cf_units with my changes this week/weekend.

**Comment by ocefpaf** [comment]
@lukecampbell Looking forward to see these changes!

**Pull request merged**
