### PR TITLE
Latest geopandas

### PR DESCRIPTION
**Pull request by ocefpaf**
Ping @emiliom. The `conda-forge` version must be the latest release but we can relax that rule here. Let me know if that works for you.

### CODE REVIEW

**Comment by emiliom** [comment]
You mean using github master branch here, right? Yes, I think that's a good idea! The geopandas master branch has been fairly stable for a long time, I think. What's being worked on before a 0.2 release is mainly documentation (it's very outdated), I think; and small loose ends.

I actually was about to ask you about geopandas on the ODM2/BiGCZ conda recipes. But I think it's best to just update it here (IOOS recipes & channel) based on github master, then pick it up from conda-forge once an official 0.2 release is made.

Thanks!

**Comment by ocefpaf** [comment]
> You mean using github master branch here, right?

Yes. I pinned to the latest commit (which is latest master today) so we can have reproducible builds. If I use `master` you never know exactly what went there unless you have the precise time of the `git clone` used in the build.

> I actually was about to ask you about geopandas on the ODM2/BiGCZ conda recipes. But I think it's best to just update it here (IOOS recipes & channel) based on github master, then pick it up from conda-forge once an official 0.2 release is made.

Agreed.

**Comment by emiliom** [comment]
>  I pinned to the latest commit (which is latest master today) so we can have reproducible builds. If I use master you never know exactly what went there unless you have the precise time of the git clone used in the build.

Ah, yes, that makes perfect sense. Learning something every day.

**Comment by emiliom** [comment]
FYI, at https://anaconda.org/IOOS/geopandas it looks like there's no build for OSX. Same for https://anaconda.org/IOOS/fiona (I assume Fiona is a geopandas dependency).

**Comment by ocefpaf** [comment]
They are being built. See https://travis-ci.org/ioos/conda-recipes for the progress.

The problem is that Travis-CI, used for the OS X builds, limits the log to 4 MB and `gdal` exceeds that. So I need to hit re-start after each build.

**Comment by emiliom** [comment]
> The problem is that Travis-CI, used for the OS X builds, limits the log to 4 MB and gdal exceeds that. So I need to hit re-start after each build.

Is there a paid subscription/option at Travis-CI that would increase the log limit and make the gdal build more automated (and less painful!)?

**Comment by ocefpaf** [comment]
> Is there a paid subscription/option at Travis-CI that would increase the log limit and make the gdal build more automated (and less painful!)?

I am not sure if the log limitation is improved in the paid version, but that is not too painful (and there workarounds that I was too lazy to implement.) It happens only with `gdal`. In conda-forge we build way more complex stuff using the free account without a problem.

**Comment by emiliom** [comment]
> I am not sure if the log limitation is improved in the paid version, but that is not too painful (and there workarounds that I was too lazy to implement.) It happens only with gdal. In conda-forge we build way more complex stuff using the free account without a problem.

Good. I won't get out my wallet yet :relieved:

**Pull request merged**
