### PR TITLE
Updated flopy to 3.2.3

### PR DESCRIPTION
**Pull request by jdhughes-usgs**
Update meta.yaml to use version 3.2.3

### CODE REVIEW

**Comment by pelson** [comment]
Looks like you didn't tag the repo yet so the build can't get the correct source.

**Comment by ocefpaf** [comment]
@jdhughes-usgs I saw that flopy is available at PyPI.  So if you do not want to tag it on GitHub you can change the `git_url` and `git_tag` lines to:

```yaml
source:
    fn: flopy-3.2.3.zip
    url: https://pypi.python.org/packages/source/f/flopy/flopy-3.2.3.zip
    md5: b49ffe2b7ee0806d4cc15824057fde58
```

**Comment by jdhughes-usgs** [comment]
Tagged the git repo.

**Comment by ocefpaf** [comment]
Thanks @jdhughes-usgs I re-started the CIs.

**Pull request merged**
