### PR TITLE
Bump build number.

### PR DESCRIPTION
**Pull request by ocefpaf**
This complements PR #88.

### CODE REVIEW

**Comment by ocefpaf** [comment]
Just to illustrate this.  (We can use this thread as an example later, when writing some docs.)

PR #88 did not bump the build number:
https://travis-ci.org/ioos/conda-recipes/builds/51626433#L323

PR #89 incremented the build number:
https://travis-ci.org/ioos/conda-recipes/builds/51634104#L323

**Comment by rsignell-usgs** [comment]
Is there any limit on the build number?  :smiley_cat:

**Comment by ocefpaf** [comment]
In theory no.  But the best practice is to reset the **build number** when updating the **version number** of a package.

Higher package version takes precedence over lower package version no matter the build number of the lower version number.  Higher build number takes precedence over lower build number only for the same package version.

**Comment by rsignell-usgs** [comment]
Okay, thanks for the explanation!

**Pull request merged**
